name: Mirror from Gitlab
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    #- cron:  '0 0 * * *'
    - cron:  '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror https://gitlab.ics.muni.cz/467814/magicforcefield-pipeline.git
        cd magicforcefield-pipeline.git
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git push --mirror github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
